model_name_or_path: "outputs/aya-vision-32b-americas"
local_dataset_path: "data/americasnlp2026"
train_split: "train"
eval_split: "validation"
source_column: "es"
target_column: "target"
bidirectional_translation: true

output_dir: "outputs/aya-vision-32b-americas-lora-grpo"
auto_resume_from_checkpoint: true
# resume_from_checkpoint: "outputs/aya-vision-32b-americas-lora-grpo/checkpoint-750"
max_completion_length: 256
num_generations: 8
temperature: 0.9
ds3_gather_for_generation: false
# top_p: 1.0
# top_k: 0
# beta: 0.0
language_sampling_alpha: 0.3

per_device_train_batch_size: 20
per_device_eval_batch_size: 20
gradient_accumulation_steps: 1
learning_rate: 1.0e-6
num_train_epochs: 60
warmup_ratio: 0.03
# weight_decay: 0.0
lr_scheduler_type: "linear"

logging_steps: 10
save_steps: 10
eval_steps: 10
save_total_limit: 3
save_only_model: false
early_stopping_patience: 3
early_stopping_threshold: 0.0005

bf16: true
fp16: false
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
deepspeed: "configs/deepspeed_lora_zero3.json"
ddp_find_unused_parameters: false

seed: 42
report_to: "none"
